### ISSUE TITLE
can't livestream youtou.be streams

### ISSUE THREAD

**Issue by gr4ssi** [info-beamer/package-livestream#4]
Hi,
just tried to live stream Live Feed #2! Iceland Volcanic Eruption from https://youtu.be/6NIt6ibAD6I and also others from www.youtube.com and .be, and nothing happens.
setup 217917 is African Watering hole https://www.youtube.com/watch?v=6NIt6ibAD6I ..

**Comment by dividuum** [comment]
Should be fixed now. I've updated the bundled streamlink code to version 2.1.2 and the Watering hole stream works for me now.

To update your package, click on the "Check for updates" button on the package page in your account. It will fetch all required changes.
