### ISSUE TITLE
Twitch Stream is flapping

### ISSUE THREAD

**Issue by gr4ssi** [info-beamer/package-livestream#5]
Hi Florian,
tried to stream different Twitch channels today (over WiFi as well as LAN 1000Mbit). All had the issue that they were constantly stopping and restarting. With Vimeo, I didn't have any issues. Could you please test if you have the same issue?
Cheers
 Marcus

**Comment by dividuum** [comment]
Hm. Not sure I can reproduce this on a Pi4. Sometimes there are micro stutters, but I don't observe by major stopping and restarting. I assume you're using the latest version of the package? Which Pi do you use?

**Comment by gr4ssi** [comment]
Strange, today it's running like sliced bread. Can't reproduce either... Thanks for having a look.
(I have a Pi 4, to answer your question.)

Ah, just remembered... I put a LAN cable in today... Maybe that makes the difference... Duh!
